import { NextResponse } from 'next/server';

// app/api/candidates/route.ts

export async function GET() {
    const candidates = [
      { id: 'abalos-benhur', name: 'ABALOS, Benhur', party: 'PFP', image: '/static/images/abalos-benhur.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/benhur-abalos/' },
      { id: 'adonis-jerome', name: 'ADONIS, Jerome', party: 'MKBYN', image: '/static/images/adonis-jerome.jpeg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/jerome-adonis/' },
      { id: 'amad-wilson', name: 'AMAD, Wilson', party: 'Independent', image: '/static/images/amad-wilson.jpeg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/wilson-amad/' },
      { id: 'andamo-nars-alyn', name: 'ANDAMO, Nars Alyn', party: 'MKBYN', image: '/static/images/andamo-lyn.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/nars-alyn-andamo/' },
      { id: 'aquino-bam', name: 'AQUINO, Paolo "Bam" Benigno IV', party: 'KNP', image: '/static/images/bam-aquino.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/bam-aquino/' },
      { id: 'arambulo-ronnel', name: 'ARAMBULO, Ronnel', party: 'MKBYN', image: '/static/images/arambulo-ronnel.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/ronnel-isdabest-arambulo/' },
      { id: 'arellano-ernesto', name: 'ARELLANO, Ernesto', party: 'KTPNAN', image: '/static/images/arellano-ernesto.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/ernesto-lawin-arellano/' },
      { id: 'ballon-roberto', name: 'BALLON, Roberto', party: 'Independent', image: '/static/images/ballon-roberto.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/roberto-ka-dodoy-ballon/' },
      { id: 'binay-abby', name: 'BINAY, Abby', party: 'NPC', image: '/static/images/binay-abby.png', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/abby-binay/' },
      { id: 'bondoc-jimmy', name: 'BONDOC, Jimmy', party: 'PDPLBN', image: '/static/images/bondoc-jimmy.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/jimmy-bondoc/' },
      { id: 'revilla-bong', name: 'REVILLA, Ramon Jr.', party: 'Lakas', image: '/static/images/revilla-bong.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/ramon-bong-revilla-jr/' },
      { id: 'bosita-colonel', name: 'BOSITA, Colonel', party: 'Independent', image: '/static/images/bosita-colonel.png', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/colonel-bosita/' },
      { id: 'brosas-arlene', name: 'BROSAS, Arlene', party: 'MKBYN', image: '/static/images/brosas-arlene.png', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/arlene-gabriela-brosas/' },
      { id: 'cabonegro-roy', name: 'CABONEGRO, Roy', party: 'DPP', image: '/static/images/cabonegro-roy.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/roy-jerusalem-cabonegro/' },
      { id: 'capuyan-allen', name: 'CAPUYAN, Allen', party: 'PPP', image: '/static/images/capuyan-allen.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/allen-capuyan/' },
      { id: 'casino-teddy', name: 'CASIÑO, Teddy', party: 'MKBYN', image: '/static/images/casino-teddy.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/teddy-casino/' },
      { id: 'castro-france', name: 'CASTRO, Teacher France', party: 'MKBYN', image: '/static/images/castro-france.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/teacher-france-castro/' },
      { id: 'cayetano-pia', name: 'CAYETANO, Pia', party: 'NP', image: '/static/images/cayetano-pia.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/pia-cayetano/' },
      { id: 'dangelo-david', name: "D'ANGELO, David", party: 'BUNYOG', image: '/static/images/dangelo-david.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/david-dangelo/' },
      { id: 'de-alban-angelo', name: 'DE ALBAN, Attorney Angelo', party: 'Independent', image: '/static/images/de-alban-angelo.png', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/attorney-angelo-de-alban/' },
      { id: 'de-guzman-leody', name: 'DE GUZMAN, Ka Leody', party: 'PLM', image: '/static/images/de-guzman-leody.png', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/ka-leody-de-guzman/' },
      { id: 'dela-rosa-bato', name: 'DELA ROSA, Ronald "Bato"', party: 'PDPLBN', image: '/static/images/dela-rosa-bato.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/bato-dela-rosa/' },
      { id: 'doringo-mimi', name: 'DORINGO, Nanay Mimi', party: 'MKBYN', image: '/static/images/doringo-mimi.png', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/nanay-mimi-doringo/' },
      { id: 'escobal-arnel', name: 'ESCOBAL, Arnel', party: 'PM', image: '/static/images/escobal-arnel.png', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/arnel-escobal/' },
      { id: 'espiritu-luke', name: 'ESPIRITU, Luke', party: 'PLM', image: '/static/images/espiritu-luke.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/luke-espiritu/' },
      { id: 'floranda-mody', name: 'FLORANDA, Mody PISTON', party: 'MKBYN', image: '/static/images/floranda-mody.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/mody-piston-floranda/' },
      { id: 'gamboa-marc', name: 'GAMBOA, Marc Louie', party: 'Independent', image: '/static/images/gamboa-marc.png', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/marc-the-vlogger-gamboa/' },
      { id: 'go-bong', name: 'GO, Bong Go', party: 'PDPLBN', image: '/static/images/go-bong.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/bong-go/' },
      { id: 'gonzales-norberto', name: 'GONZALES, Norberto', party: 'PDSP', image: '/static/images/gonzales-norberto.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/norberto-gonzales/' },
      { id: 'hinlo-jayvee', name: 'HINLO, Jayvee', party: 'PDPLBN', image: '/static/images/hinlo-jayvee.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/jayvee-hinlo/' },
      { id: 'honasan-gringo', name: 'HONASAN, Gringo', party: 'RP', image: '/static/images/honasan_gringo.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/gringo-honasan/' },
      { id: 'jose-relly', name: 'JOSE, Relly Jr.', party: 'KBL', image: '/static/images/jose-relly.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/relly-jose-jr/' },
      { id: 'lacson-ping', name: 'LACSON, Ping', party: 'Independent', image: '/static/images/lacson-ping.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/ping-lacson/' },
      { id: 'lambino-raul', name: 'LAMBINO, Raul', party: 'PDPLBN', image: '/static/images/lambino-raul.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/raul-kabaka-lambino/' },
      { id: 'lapid-lito', name: 'LAPID, Lito', party: 'NPC', image: '/static/images/lapid-lito.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/lito-lapid/' },
      { id: 'lidasan-amirah', name: 'LIDASAN, Amirah', party: 'MKBYN', image: '/static/images/lidasan-amirah.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/amirah-mek-lidasan/' },
      { id: 'marcoleta-rodante', name: 'MARCOLETA, Rodante', party: 'Independent', image: '/static/images/marcoleta-rodante.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/rodante-marcoleta/' },
      { id: 'marcos-imee', name: 'MARCOS, Imee', party: 'NP', image: '/static/images/marcos-imee.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/imee-r-marcos/' },
      { id: 'marquez-norman', name: 'MARQUEZ, Norman', party: 'Independent', image: '/static/images/marquez-norman.jpeg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/norman-marquez/' },
      { id: 'martinez-eric', name: 'MARTINEZ, Eric', party: 'Independent', image: '/static/images/martinez-eric.jpeg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/eric-martinez/' },
      { id: 'mata-marites', name: 'MATA, Doc Marites', party: 'Independent', image: '/static/images/mata-marites.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/doc-marites-mata/' },
      { id: 'matula-sonny', name: 'MATULA, Atty. Sonny', party: 'WPP', image: '/static/images/matula-sonny.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/atty-sonny-matula/' },
      { id: 'maza-liza', name: 'MAZA, Liza', party: 'MKBYN', image: '/static/images/maza-liza.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/liza-maza-/' },
      { id: 'mendoza-heidi', name: 'MENDOZA, Heidi', party: 'Independent', image: '/static/images/mendoza-heidi.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/heidi-mendoza/' },
      { id: 'montemayor-joey', name: 'MONTEMAYOR, Joey', party: 'Independent', image: '/static/images/montemayor-joey.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/joey-montemayor/' },
      { id: 'mustapha-subair', name: 'MUSTAPHA, Subair', party: 'WPP', image: '/static/images/mustapha-subair.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/sultan-bert-mustapha/' },
      { id: 'pacquiao-manny', name: 'PACQUIAO, Manny Pacman', party: 'PFP', image: '/static/images/pacquiao_manny.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/manny-pacman-pacquiao/' },
      { id: 'pangilinan-kiko', name: 'PANGILINAN, Francis "Kiko"', party: 'KNP', image: '/static/images/pangilinan-kiko.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/kiko-pangilinan/' },
      { id: 'querubin-ariel', name: 'QUERUBIN, Ariel Porfirio', party: 'NP', image: '/static/images/querubin-ariel.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/ariel-bayani-natin-querubin/' },
      { id: 'quiboloy-apollo', name: 'QUIBOLOY, Apollo', party: 'Independent', image: '/static/images/quiboloy-apollo.jpeg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/apollo-carreon-quiboloy--/' },
      { id: 'ramos-danilo', name: 'RAMOS, Danilo', party: 'MKBYN', image: '/static/images/ramos-danilo.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/danilo-ka-daning-ramos/' },
      { id: 'revillame-willie', name: 'REVILLAME, Willie Wil', party: 'Independent', image: '/static/images/revillame-willie.png', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/willie-wil-revillame/' },
      { id: 'rodriguez-vic', name: 'RODRIGUEZ, Atty. Vic', party: 'Independent', image: '/static/images/rodriguez-vic.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/atty-vic-rodriguez/' },
      { id: 'sahidulla-nurana', name: 'SAHIDULLA, Nur-Ana', party: 'Independent', image: '/static/images/sahidulla-nurana.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/nur-ana-sahidulla/' },
      { id: 'salvador-phillip', name: 'SALVADOR, Phillip Ipe', party: 'PDPLBN', image: '/static/images/salvador-phillip.png', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/phillip-ipe-salvador/' },
      { id: 'sotto-tito', name: 'SOTTO, Tito', party: 'NPC', image: '/static/images/sotto-tito.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/tito-sotto/' },
      { id: 'tapado-michael', name: 'TAPADO, Michael Bongbong', party: 'PM', image: '/static/images/tapado-michael.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/francis-tol-tolentino/' },
      { id: 'tolentino-francis', name: 'TOLENTINO, Francis', party: 'PFP', image: '/static/images/tolentino-francis.jpeg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/francis-tol-tolentino/' },
      { id: 'tulfo-ben', name: 'TULFO, Ben Bitag', party: 'Independent', image: '/static/images/tulfo-ben.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/ben-bitag-tulfo/' },
      { id: 'tulfo-erwin', name: 'TULFO, Erwin', party: 'Lakas', image: '/static/images/tulfo-erwin.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/erwin-tulfo/' },
      { id: 'valbuena-mar', name: 'VALBUENA, Mar Manibela', party: 'Independent', image: '/static/images/valbuena-mar.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/mar-manibela-valbuena/' },
      { id: 'verceles-leandro', name: 'VERCELES, Leandro', party: 'Independent', image: '/static/images/verceles-leandro.jpg', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/leandro-verceles-jr/' },
      { id: 'villar-camille', name: 'VILLAR, Camille', party: 'NP', image: '/static/images/villar-camille.webp', gmaProfileLink: 'https://www.gmanetwork.com/news/eleksyon/2025/candidates/camille-villar/' }
    ];
  
    return NextResponse.json(candidates);
  }
  