import { NextResponse } from 'next/server';

// app/api/candidates/route.ts

export async function GET() {
    const candidates = [
      { id: 'abalos-benhur', name: 'ABALOS, Benhur', party: 'PFP', image: '/static/images/abalos-benhur.jpg' },
      { id: 'adonis-jerome', name: 'ADONIS, Jerome', party: 'MKBYN', image: '/static/images/adonis-jerome.jpeg' },
      { id: 'amad-wilson', name: 'AMAD, Wilson', party: 'Independent', image: '/static/images/amad-wilson.jpeg' },
      { id: 'andamo-nars-alyn', name: 'ANDAMO, Nars Alyn', party: 'MKBYN', image: '/static/images/andamo-lyn.jpg' },
      { id: 'aquino-bam', name: 'AQUINO, Paolo "Bam" Benigno IV', party: 'KNP', image: '/static/images/bam-aquino.jpg' },
      { id: 'arambulo-ronnel', name: 'ARAMBULO, Ronnel', party: 'MKBYN', image: '/static/images/arambulo-ronnel.jpg' },
      { id: 'arellano-ernesto', name: 'ARELLANO, Ernesto', party: 'KTPNAN', image: '/static/images/arellano-ernesto.jpg' },
      { id: 'ballon-roberto', name: 'BALLON, Roberto', party: 'Independent', image: '/static/images/ballon-roberto.jpg' },
      { id: 'binay-abby', name: 'BINAY, Abby', party: 'NPC', image: '/static/images/binay-abby.png' },
      { id: 'bondoc-jimmy', name: 'BONDOC, Jimmy', party: 'PDPLBN', image: '/static/images/bondoc-jimmy.jpg' },
      { id: 'revilla-bong', name: 'REVILLA, Ramon Jr.', party: 'Lakas', image: '/static/images/revilla-bong.jpg' },
      { id: 'bosita-colonel', name: 'BOSITA, Colonel', party: 'Independent', image: '/static/images/bosita-colonel.png' },
      { id: 'brosas-arlene', name: 'BROSAS, Arlene', party: 'MKBYN', image: '/static/images/brosas-arlene.png' },
      { id: 'cabonegro-roy', name: 'CABONEGRO, Roy', party: 'DPP', image: '/static/images/cabonegro-roy.jpg' },
      { id: 'capuyan-allen', name: 'CAPUYAN, Allen', party: 'PPP', image: '/static/images/capuyan-allen.jpg' },
      { id: 'casino-teddy', name: 'CASIÑO, Teddy', party: 'MKBYN', image: '/static/images/casino-teddy.jpg' },
      { id: 'castro-france', name: 'CASTRO, Teacher France', party: 'MKBYN', image: '/static/images/castro-france.jpg' },
      { id: 'cayetano-pia', name: 'CAYETANO, Pia', party: 'NP', image: '/static/images/cayetano-pia.jpg' },
      { id: 'dangelo-david', name: "D'ANGELO, David", party: 'BUNYOG', image: '/static/images/dangelo-david.jpg' },
      { id: 'de-alban-angelo', name: 'DE ALBAN, Attorney Angelo', party: 'Independent', image: '/static/images/de-alban-angelo.png' },
      { id: 'de-guzman-leody', name: 'DE GUZMAN, Ka Leody', party: 'PLM', image: '/static/images/de-guzman-leody.png' },
      { id: 'dela-rosa-bato', name: 'DELA ROSA, Ronald "Bato"', party: 'PDPLBN', image: '/static/images/dela-rosa-bato.webp' },
      { id: 'doringo-mimi', name: 'DORINGO, Nanay Mimi', party: 'MKBYN', image: '/static/images/doringo-mimi.png' },
      { id: 'escobal-arnel', name: 'ESCOBAL, Arnel', party: 'PM', image: '/static/images/escobal-arnel.png' },
      { id: 'espiritu-luke', name: 'ESPIRITU, Luke', party: 'PLM', image: '/static/images/espiritu-luke.jpg' },
      { id: 'floranda-mody', name: 'FLORANDA, Mody PISTON', party: 'MKBYN', image: '/static/images/floranda-mody.jpg' },
      { id: 'gamboa-marc', name: 'GAMBOA, Marc Louie', party: 'Independent', image: '/static/images/gamboa-marc.png' },
      { id: 'go-bong', name: 'GO, Bong Go', party: 'PDPLBN', image: '/static/images/go-bong.webp' },
      { id: 'gonzales-norberto', name: 'GONZALES, Norberto', party: 'PDSP', image: '/static/images/gonzales-norberto.jpg' },
      { id: 'hinlo-jayvee', name: 'HINLO, Jayvee', party: 'PDPLBN', image: '/static/images/hinlo-jayvee.webp' },
      { id: 'honasan-gringo', name: 'HONASAN, Gringo', party: 'RP', image: '/static/images/honasan_gringo.jpg' },
      { id: 'jose-relly', name: 'JOSE, Relly Jr.', party: 'KBL', image: '/static/images/jose-relly.webp' },
      { id: 'lacson-ping', name: 'LACSON, Ping', party: 'Independent', image: '/static/images/lacson-ping.webp' },
      { id: 'lambino-raul', name: 'LAMBINO, Raul', party: 'PDPLBN', image: '/static/images/lambino-raul.webp' },
      { id: 'lapid-lito', name: 'LAPID, Lito', party: 'NPC', image: '/static/images/lapid-lito.jpg' },
      { id: 'lidasan-amirah', name: 'LIDASAN, Amirah', party: 'MKBYN', image: '/static/images/lidasan-amirah.webp' },
      { id: 'marcoleta-rodante', name: 'MARCOLETA, Rodante', party: 'Independent', image: '/static/images/marcoleta-rodante.jpg' },
      { id: 'marcos-imee', name: 'MARCOS, Imee', party: 'NP', image: '/static/images/marcos-imee.jpg' },
      { id: 'marquez-norman', name: 'MARQUEZ, Norman', party: 'Independent', image: '/static/images/marquez-norman.jpeg' },
      { id: 'martinez-eric', name: 'MARTINEZ, Eric', party: 'Independent', image: '/static/images/martinez-eric.jpeg' },
      { id: 'mata-marites', name: 'MATA, Doc Marites', party: 'Independent', image: '/static/images/mata-marites.webp' },
      { id: 'matula-sonny', name: 'MATULA, Atty. Sonny', party: 'WPP', image: '/static/images/matula-sonny.webp' },
      { id: 'maza-liza', name: 'MAZA, Liza', party: 'MKBYN', image: '/static/images/maza-liza.webp' },
      { id: 'mendoza-heidi', name: 'MENDOZA, Heidi', party: 'Independent', image: '/static/images/mendoza-heidi.webp' },
      { id: 'montemayor-joey', name: 'MONTEMAYOR, Joey', party: 'Independent', image: '/static/images/montemayor-joey.webp' },
      { id: 'mustapha-subair', name: 'MUSTAPHA, Subair', party: 'WPP', image: '/static/images/mustapha-subair.webp' },
      { id: 'pacquiao-manny', name: 'PACQUIAO, Manny Pacman', party: 'PFP', image: '/static/images/pacquiao_manny.jpg' },
      { id: 'pangilinan-kiko', name: 'PANGILINAN, Francis "Kiko"', party: 'KNP', image: '/static/images/pangilinan-kiko.jpg' },
      { id: 'querubin-ariel', name: 'QUERUBIN, Ariel Porfirio', party: 'NP', image: '/static/images/querubin-ariel.webp' },
      { id: 'quiboloy-apollo', name: 'QUIBOLOY, Apollo', party: 'Independent', image: '/static/images/quiboloy-apollo.jpeg' },
      { id: 'ramos-danilo', name: 'RAMOS, Danilo', party: 'MKBYN', image: '/static/images/ramos-danilo.jpg' },
      { id: 'revillame-willie', name: 'REVILLAME, Willie Wil', party: 'Independent', image: '/static/images/revillame-willie.png' },
      { id: 'rodriguez-vic', name: 'RODRIGUEZ, Atty. Vic', party: 'Independent', image: '/static/images/rodriguez-vic.jpg' },
      { id: 'sahidulla-nurana', name: 'SAHIDULLA, Nur-Ana', party: 'Independent', image: '/static/images/sahidulla-nurana.webp' },
      { id: 'salvador-phillip', name: 'SALVADOR, Phillip Ipe', party: 'PDPLBN', image: '/static/images/salvador-phillip.png' },
      { id: 'sotto-tito', name: 'SOTTO, Tito', party: 'NPC', image: '/static/images/sotto-tito.jpg' },
      { id: 'tapado-michael', name: 'TAPADO, Michael Bongbong', party: 'PM', image: '/static/images/tapado-michael.webp' },
      { id: 'tolentino-francis', name: 'TOLENTINO, Francis', party: 'PFP', image: '/static/images/tolentino-francis.jpeg' },
      { id: 'tulfo-ben', name: 'TULFO, Ben Bitag', party: 'Independent', image: '/static/images/tulfo-ben.jpg' },
      { id: 'tulfo-erwin', name: 'TULFO, Erwin', party: 'Lakas', image: '/static/images/tulfo-erwin.jpg' },
      { id: 'valbuena-mar', name: 'VALBUENA, Mar Manibela', party: 'Independent', image: '/static/images/valbuena-mar.webp' },
      { id: 'verceles-leandro', name: 'VERCELES, Leandro', party: 'Independent', image: '/static/images/verceles-leandro.jpg' },
      { id: 'villar-camille', name: 'VILLAR, Camille', party: 'NP', image: '/static/images/villar-camille.webp' }
    ];
  
    return NextResponse.json(candidates);
  }
  